FROM node:24-bookworm-slim

ENV NODE_ENV=development \
    PNPM_HOME=/pnpm \
    PATH=/pnpm:$PATH \
    HUSKY=0

RUN npm install -g pnpm@11.1.1 \
  && apt-get update -y \
  && apt-get install -y --no-install-recommends openssl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/api/prisma.config.ts ./apps/api/prisma.config.ts
COPY apps/api/prisma/ ./apps/api/prisma/

RUN pnpm install --filter hackathon-star-nest... --frozen-lockfile

EXPOSE 3001

CMD ["pnpm", "--dir", "apps/api", "start:dev"]
